<?php

return [
    'per_page' => 12,
    'entries' => [
        ['number' => '00', 'slug' => 'bulan', 'title' => 'Bulan', 'keywords' => ['malam', 'cahaya', 'langit'], 'interpretation' => 'Simbol ketenangan, siklus baru, dan pertimbangan yang matang.'],
        ['number' => '01', 'slug' => 'matahari', 'title' => 'Matahari', 'keywords' => ['pagi', 'terang', 'energi'], 'interpretation' => 'Simbol semangat, kejelasan, dan awal yang penuh energi.'],
        ['number' => '02', 'slug' => 'bintang', 'title' => 'Bintang', 'keywords' => ['langit', 'harapan', 'petunjuk'], 'interpretation' => 'Simbol harapan, arah, dan tujuan yang ingin dicapai.'],
        ['number' => '03', 'slug' => 'hujan', 'title' => 'Hujan', 'keywords' => ['air', 'cuaca', 'sejuk'], 'interpretation' => 'Simbol pembaruan, pelepasan beban, dan kesegaran.'],
        ['number' => '04', 'slug' => 'pelangi', 'title' => 'Pelangi', 'keywords' => ['warna', 'langit', 'hujan'], 'interpretation' => 'Simbol optimisme, perubahan baik, dan keberagaman peluang.'],
        ['number' => '05', 'slug' => 'gunung', 'title' => 'Gunung', 'keywords' => ['tinggi', 'alam', 'puncak'], 'interpretation' => 'Simbol tantangan, keteguhan, dan pencapaian bertahap.'],
        ['number' => '06', 'slug' => 'laut', 'title' => 'Laut', 'keywords' => ['air', 'ombak', 'pantai'], 'interpretation' => 'Simbol kedalaman perasaan, keluasan pilihan, dan perubahan.'],
        ['number' => '07', 'slug' => 'sungai', 'title' => 'Sungai', 'keywords' => ['air', 'arus', 'perjalanan'], 'interpretation' => 'Simbol perjalanan, kelancaran, dan kemampuan beradaptasi.'],
        ['number' => '08', 'slug' => 'pohon', 'title' => 'Pohon', 'keywords' => ['daun', 'akar', 'hutan'], 'interpretation' => 'Simbol pertumbuhan, fondasi yang kuat, dan keberlanjutan.'],
        ['number' => '09', 'slug' => 'bunga', 'title' => 'Bunga', 'keywords' => ['mekar', 'harum', 'taman'], 'interpretation' => 'Simbol perkembangan, perhatian, dan hasil dari perawatan.'],
        ['number' => '10', 'slug' => 'burung', 'title' => 'Burung', 'keywords' => ['terbang', 'sayap', 'langit'], 'interpretation' => 'Simbol kebebasan, kabar, dan sudut pandang baru.'],
        ['number' => '11', 'slug' => 'ikan', 'title' => 'Ikan', 'keywords' => ['air', 'kolam', 'laut'], 'interpretation' => 'Simbol keluwesan, sumber daya, dan peluang tersembunyi.'],
        ['number' => '12', 'slug' => 'kucing', 'title' => 'Kucing', 'keywords' => ['hewan', 'rumah', 'lincah'], 'interpretation' => 'Simbol kemandirian, kepekaan, dan kehati-hatian.'],
        ['number' => '13', 'slug' => 'anjing', 'title' => 'Anjing', 'keywords' => ['hewan', 'setia', 'sahabat'], 'interpretation' => 'Simbol kesetiaan, perlindungan, dan hubungan yang dapat dipercaya.'],
        ['number' => '14', 'slug' => 'kuda', 'title' => 'Kuda', 'keywords' => ['hewan', 'cepat', 'perjalanan'], 'interpretation' => 'Simbol daya gerak, keberanian, dan kemajuan.'],
        ['number' => '15', 'slug' => 'rumah', 'title' => 'Rumah', 'keywords' => ['tempat tinggal', 'keluarga', 'aman'], 'interpretation' => 'Simbol keamanan, identitas, dan kehidupan pribadi.'],
        ['number' => '16', 'slug' => 'jalan', 'title' => 'Jalan', 'keywords' => ['arah', 'perjalanan', 'tujuan'], 'interpretation' => 'Simbol pilihan, proses, dan arah yang sedang ditempuh.'],
        ['number' => '17', 'slug' => 'jembatan', 'title' => 'Jembatan', 'keywords' => ['penghubung', 'sungai', 'jalan'], 'interpretation' => 'Simbol transisi, penyelesaian jarak, dan hubungan baru.'],
        ['number' => '18', 'slug' => 'kapal', 'title' => 'Kapal', 'keywords' => ['laut', 'perjalanan', 'pelabuhan'], 'interpretation' => 'Simbol perjalanan besar, ketahanan, dan tujuan jauh.'],
        ['number' => '19', 'slug' => 'kereta', 'title' => 'Kereta', 'keywords' => ['transportasi', 'rel', 'stasiun'], 'interpretation' => 'Simbol ritme, jadwal, dan kemajuan yang terarah.'],
        ['number' => '20', 'slug' => 'mobil', 'title' => 'Mobil', 'keywords' => ['kendaraan', 'jalan', 'perjalanan'], 'interpretation' => 'Simbol kendali, kecepatan keputusan, dan arah pribadi.'],
        ['number' => '21', 'slug' => 'sepeda', 'title' => 'Sepeda', 'keywords' => ['kendaraan', 'roda', 'seimbang'], 'interpretation' => 'Simbol keseimbangan, usaha mandiri, dan kemajuan bertahap.'],
        ['number' => '22', 'slug' => 'buku', 'title' => 'Buku', 'keywords' => ['belajar', 'membaca', 'pengetahuan'], 'interpretation' => 'Simbol pengetahuan, catatan pengalaman, dan pembelajaran.'],
        ['number' => '23', 'slug' => 'kunci', 'title' => 'Kunci', 'keywords' => ['pintu', 'akses', 'rahasia'], 'interpretation' => 'Simbol solusi, akses, dan kesempatan untuk membuka jalan.'],
        ['number' => '24', 'slug' => 'pintu', 'title' => 'Pintu', 'keywords' => ['masuk', 'keluar', 'rumah'], 'interpretation' => 'Simbol batas, kesempatan, dan keputusan untuk melangkah.'],
        ['number' => '25', 'slug' => 'jam', 'title' => 'Jam', 'keywords' => ['waktu', 'jadwal', 'detik'], 'interpretation' => 'Simbol ketepatan, tenggat, dan kesadaran terhadap waktu.'],
        ['number' => '26', 'slug' => 'cermin', 'title' => 'Cermin', 'keywords' => ['pantulan', 'wajah', 'kaca'], 'interpretation' => 'Simbol evaluasi diri, kejujuran, dan sudut pandang.'],
        ['number' => '27', 'slug' => 'payung', 'title' => 'Payung', 'keywords' => ['hujan', 'pelindung', 'cuaca'], 'interpretation' => 'Simbol perlindungan, kesiapan, dan antisipasi.'],
        ['number' => '28', 'slug' => 'lilin', 'title' => 'Lilin', 'keywords' => ['api', 'cahaya', 'malam'], 'interpretation' => 'Simbol harapan kecil, fokus, dan ketenangan.'],
        ['number' => '29', 'slug' => 'api', 'title' => 'Api', 'keywords' => ['panas', 'cahaya', 'energi'], 'interpretation' => 'Simbol tenaga, perubahan cepat, dan motivasi kuat.'],
        ['number' => '30', 'slug' => 'nasi', 'title' => 'Nasi', 'keywords' => ['makanan', 'dapur', 'hidangan'], 'interpretation' => 'Simbol kebutuhan dasar, kecukupan, dan hasil kerja.'],
        ['number' => '31', 'slug' => 'buah', 'title' => 'Buah', 'keywords' => ['makanan', 'panen', 'segar'], 'interpretation' => 'Simbol hasil, kesehatan, dan manfaat dari proses panjang.'],
    ],
];
